services:
  db:
    image: mysql:8.0
    container_name: sanctuary-db
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sanctuary_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sanctuary-net
    restart: always

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: sanctuary-pma
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8888:80"
    depends_on:
      - db
    networks:
      - sanctuary-net

  backend:
    build: ./backend
    container_name: sanctuary-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - db
    networks:
      - sanctuary-net

  engine:
    build: ./engine
    container_name: sanctuary-engine
    ports:
      - "8080:8080"
    volumes:
      - ./engine:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
    working_dir: /app
    networks:
      - sanctuary-net
    # command: cargo watch -x run

networks:
  sanctuary-net:
    driver: bridge

volumes:
  db_data:
  cargo_cache:
  target_cache: